### PR TITLE
Support for D51, E51 and E54

### PR DESCRIPTION
**Pull request by ericbaril72**
So far so good.... need someone else to double check.

Have not tested the "sleep()" method
My Setup is the SAME54 but they work identical ( D51, E51 and E54 )

--> Needs defined(ARDUINO_ARCH_SAMD)
but the register set of D21 vs D51 is just "similar" not stupid-proof to port.

### CODE REVIEW

**Comment by ladyada** [comment]
thankx :)

**Comment by PaintYourDragon** [comment]
Looks encouraging, thanks. I'll be testing some other stuff soon anyway and will verify.

**Comment by PaintYourDragon** [comment]
Not working as expected on M4. Doesn't crash, so that much is good, but it doesn't sleep, or the interval is very short.

**Comment by PaintYourDragon** [comment]
There's apparently a reliability issue with the code on M0. I'm gonna take a look through the latest ASF library and see how they're handling sleep on both devices...maybe it'll fix one or both.

**Pull request merged**
